###
POST http://localhost:3000/admins/agregarAdmin HTTP/1.1
Content-Type: application/json

{
    "id_admin":11,
    "nombre":"pao 3",
    "password":"789"
}

###
GET http://localhost:3000/admins/ HTTP/1.1
Content-Type: application/json

{
    "id_admin":2
}

###
DELETE http://localhost:3000/admins/eliminarAdmin HTTP/1.1
Content-Type: application/json

{
    "id_admin":1
}