###
POST http://localhost:3000/cliente/agregarCliente HTTP/1.1
Content-Type: application/json

{
    "id_cliente":3,
    "nombre":"Luis"
}

###
DELETE http://localhost:3000/cliente/eliminarCliente HTTP/1.1
Content-Type: application/json

{
    "id_cliente":3
}