###
POST http://localhost:3000/clientes/agregarCliente HTTP/1.1
Content-Type: application/json

{
    "id_cliente":1,
    "nombre":"Paolis"
}

###
DELETE http://localhost:3000/clientes/eliminarCliente HTTP/1.1
Content-Type: application/json

{
    "id_cliente":1
}